apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: {{ .Values.db.image }}
        ports:
        - containerPort: {{ .Values.db.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.db.database | quote }}
        startupProbe:
          exec:
            command:
              - pg_isready
              - -U
              - {{ .Values.db.user | quote }}
              - -d
              - {{ .Values.db.database | quote }}
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        emptyDir: {}
