apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 # Pode manter 80 para comunicação interna
      targetPort: 5002 # Deve ser a porta que o container escuta
  type: ClusterIP