version: '3.8'

services:
  agente_app:
    build:
      context: ./agente_app
      dockerfile: Dockerfile
    container_name: agente_app
    environment:
      - GOOGLE_API_KEY=AIzaSyD1UWd_lecPss9chJbBivtmet8D8vYtvsw
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - AGENTE_APP_SERVICE=agente_app
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/postsdb
    depends_on:
      - agente_app
      - db

    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_SERVICE=backend
    depends_on:
      - backend
    networks:
      - app-network
    
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge